dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

log_path = /dev/stderr
info_log_path = /dev/stdout
debug_log_path = /dev/stdout

auth_mechanisms = plain login
mail_driver = maildir
mail_path = /var/vmail/%{user | username}@%{user | domain}/Maildir

namespace inbox {
  inbox = yes
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix =
}

passdb passwd-file {
  passwd_file_path = /etc/dovecot/users
}

userdb static {
  fields {
    uid = dockervmail
    gid = dockervmail
    home = /var/vmail/%{user | username}@%{user | domain}
  }
}

protocols = imap lmtp

service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0660
    user = postfix
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    group = postfix
    mode = 0600
    user = postfix
  }
}

ssl_server_cert_file = /etc/postfix/tls/bundle.crt
ssl_server_key_file = /etc/postfix/tls/cert.key
ssl_server_dh_file = /etc/postfix/tls/dh4096.pem
ssl_server_prefer_ciphers = server

postmaster_address = postmaster@mailbox.local

protocol lmtp {
}
